import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import cx from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const combinedClassName = cx(inter.className, "font-sans", "bg-gray-50");
  return (
    <html lang="en">
      <>
        <body className={combinedClassName}>{children}</body>
      </>
    </html>
  );
}
